### ISSUE TITLE
nobody2018 - withdrawFees() should only be called by feeRecipient

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-avail-judging#11]
nobody2018

medium

# withdrawFees() should only be called by feeRecipient

## Summary

[[withdrawFees()](https://github.com/sherlock-audit/2023-12-avail/blob/main/contracts/src/AvailBridge.sol#L171)](https://github.com/sherlock-audit/2023-12-avail/blob/main/contracts/src/AvailBridge.sol#L171) can be called by anyone. When the old feeRecipient needs to be changed, for example, the private key is lost, the admin sets a new feeRecipient via [[updateFeeRecipient](https://github.com/sherlock-audit/2023-12-avail/blob/main/contracts/src/AvailBridge.sol#L162)](https://github.com/sherlock-audit/2023-12-avail/blob/main/contracts/src/AvailBridge.sol#L162). A malicious user can call `withdrawFees()` to front-run `updateFeeRecipient`, which causes the accumulated fees to be transferred to the old address.

## Vulnerability Detail

Consider the following scenario:

The current fees being accumulated is 10 ether. The current feeRecipient is lost.

1.  The admin calls `updateFeeRecipient` to set a new feeRecipient. tx enters mempool.
2.  Bob notices this tx and immediately calls `withdrawFees()` to front-run the tx.
3.  10 ether was transferred to the old feeRecipient.
4.  feeRecipient is set to the new address.

## Impact

fees will be lost.

## Code Snippet

https://github.com/sherlock-audit/2023-12-avail/blob/main/contracts/src/AvailBridge.sol#L162-L179

## Tool used

Manual Review

## Recommendation

Add `require(msg.sender == feeRecipient)` in `withdrawFees()`.

**Comment by QEDK** [comment]
It is highly unlikely to compromise all private keys of a multisig designated as a `feeRecipient`. It is also possible to update the `feeRecipient` using a private tx to front-run an attack, as such I see this attack vector as unlikely but it is a decent recommendation imo.
