### ISSUE TITLE
0x_Scar - The AvailBridge does not refund excess ETH sent when sending message

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-avail-judging#13]
0x_Scar

medium

# The AvailBridge does not refund excess ETH sent when sending message

## Summary
The `AvailBridge` contract has a `sendMessage` function which allows for passing arbitrary data from Ethereum to Avail. The function is payable and is implemented as follows
```Solidity
    function sendMessage(bytes32 recipient, bytes calldata data) external payable whenNotPaused {
        uint256 length = data.length;
        if (length >= MAX_DATA_LENGTH) {
            revert ExceedsMaxDataLength();
        }
        // ensure that fee is above minimum amount
        if (msg.value < getFee(length)) { //@audit excess fee is not refunded
            revert FeeTooLow(); //@audit should store fee then call getFee
        }
        uint256 id;
        unchecked {
            id = messageId++;
        }
        fees += msg.value;
        Message memory message = Message(
            MESSAGE_TX_PREFIX, bytes32(bytes20(msg.sender)), recipient, ETH_DOMAIN, AVAIL_DOMAIN, data, uint64(id)
        );
        // store message hash to be retrieved later by our light client
        isSent[id] = keccak256(abi.encode(message));

        emit MessageSent(msg.sender, recipient, id);
    }
```
As seen on the contract asserts that the `msg.value` is greater than the required fee here
```Solidity
  if (msg.value < getFee(length)) { //@audit excess fee is not refunded
            revert FeeTooLow(); //@audit should store fee then call getFee
        }
```
If the `msg.value` is greater, it ends up adding the entire `msg.value` to `fees` variable as `fees += msg.value`. Therefore, if a user sends excess `ETH` in `msg.value` which is very possible, then the excess `ETH` is added as fees and is not refunded to the user. 
## Vulnerability Detail
https://github.com/sherlock-audit/2023-12-avail/blob/1afb56b8d4dfbf5d3f21bed0ddf80a04730204b5/contracts/src/AvailBridge.sol#L299-L323
## Impact
Users will lose the excess ETH sent in the transaction. 
## Code Snippet
https://github.com/sherlock-audit/2023-12-avail/blob/1afb56b8d4dfbf5d3f21bed0ddf80a04730204b5/contracts/src/AvailBridge.sol#L299-L323
## Tool used

Manual Review

## Recommendation
Consider refunding excess ETH sent or assert `msg.value == getFee(length)`

**Comment by QEDK** [comment]
This is intentional, this is designated as a user input issue i.e. a user is allowed to overpay the bridge for relaying the tx.
