### ISSUE TITLE
Anubis - Access Control (General Best Practice)

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-avail-judging#15]
Anubis

medium

# Access Control (General Best Practice)

## Summary
The contract implements a custom access control mechanism, restricting the mint and burn functions to be callable only by the bridge address.

## Vulnerability Detail
The contract's critical functions, mint and burn, are protected by a custom access control mechanism that checks if the caller is the bridge address. While this is a fundamental security measure, its effectiveness hinges entirely on the integrity and secure management of the bridge address. If the address is compromised, incorrectly set, or if there's a way for an unauthorized actor to manipulate it, it could lead to unauthorized minting or burning of tokens. This could have devastating effects on the token's economy and trustworthiness.

## Impact
If the access control is bypassed or compromised, malicious actors could mint an unlimited number of tokens or burn tokens they don't own, leading to devaluation of the token and potential loss for token holders.

## Code Snippet
https://github.com/sherlock-audit/2023-12-avail/blob/main/contracts/src/WrappedAvail.sol#L23-L36

## Tool used

Manual Review

## Recommendation
Consider using well-established patterns or libraries for access management. Ensure that the bridge address is securely managed and consider mechanisms for securely updating it if necessary.

**Comment by QEDK** [comment]
The token contract is intended to be permissionless. Adding arbitrary access control is infeasible for this use-case.
