### ISSUE TITLE
0x52 - Very large sends from AvailBridge will break receiving bridge and cause loss of funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-avail-judging#85]
0x52

medium

# Very large sends from AvailBridge will break receiving bridge and cause loss of funds

## Summary

When sending tokens, up to uint256.max can be sent by AvailBridge, however lib.rs can only receive amounts up to uint128.max. Any values over uint128.max will cause the AVAIL side of the bridge to panic and deposit will be permanently lost.

## Vulnerability Detail

[lib.rs#L394-L399](https://github.com/availproject/avail/blob/e976c560ee3f8c7d36d9fbec8e98c29283f1aa34/pallets/succinct/src/lib.rs#L394-L399)

    T::Currency::transfer(
            &Self::account_id(),
            &destination_account_id,
            amount.as_u128().saturated_into(),
            ExistenceRequirement::AllowDeath,
    )?;

When receiving a token transfer, lib.rs attempts to convert the amount from uint256 to uint128 via `as_u128()`. When amount is more than uint128.max this will panic and prevent processing of the transaction. Since the bridge doesn't have any way handle failed transactions, the deposit will be permanently lost.

## Impact

Large deposits will break the receiving end of the bridge and cause loss of funds

## Code Snippet

[AvailBridge.sol#L383-L411](https://github.com/sherlock-audit/2023-12-avail/blob/main/contracts/src/AvailBridge.sol#L383-L411)

## Tool used

Manual Review

## Recommendation

Cause all `send` functions to revert for amounts that are greater than uint128.max.

**Comment by QEDK** [comment]
We primarily use `uint256` because it's cheaper on EVM, any `uint128` transfers are highly unlikely because the total supply of all tokens is much lower than that. For e.g. taking the token with the highest supply today: `((1.774455 * (10 ** 17)) * (10 ** 18))  < type(uint128).max` would return `true`.

**Comment by IAm0x52** [comment]
Escalate

Protocol is designed to work with arbitrary ERC20 token. I've clearly shown an edge case to be addressed that causes loss of funds.

**Comment by sherlock-admin** [comment]
The protocol team fixed this issue in PR/commit https://github.com/availproject/contracts/pull/3.

**Comment by sherlock-admin** [comment]
The Lead Senior Watson signed-off on the fix.
